<a href="https://colab.research.google.com/github/crisfisico/minicurso-python/blob/main/Aula_02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## A versao em uso do Python

In [ ]:
!python --version

Python 3.7.11


## Tipos de dados

## Numerico

### inteiro: int

In [ ]:
x = 10
print("x =",x)
print(type(x))

x = 10
<class 'int'>


In [ ]:
y = int(20)
print(y)
print(type(y))

20
<class 'int'>


### decimal: float

In [ ]:
# m eh a massa da particula
m = 80.30 # [m]=kg
print(m)
print(type(m))

80.3
<class 'float'>


In [ ]:
# massa terra - notacao cientifica
massa_t = 5.972e24 # [m]=kg
print(massa_t)
print(type(massa_t))

5.972e+24
<class 'float'>


### num complexo: complex

In [ ]:
z = 9+8j
print(z)
print(type(z))

(9+8j)
<class 'complex'>


## Sequencia

### string: str

In [ ]:
my_str = 'Python' 
print(my_str)
print(type(my_str))

Python
<class 'str'>


In [ ]:
# acessando caracteres
print(my_str[0])
print(my_str[1])
print(my_str[2])
print(my_str[3])
print(my_str[4])
print(my_str[5])
#print(my_str[6]) # nao existe!

P
y
t
h
o
n


### Lista: list

In [ ]:
my_list = ['banana','abacate','laranja','pera']
print(my_list)
print(type(my_list))

['banana', 'abacate', 'laranja', 'pera']
<class 'list'>


In [ ]:
print(my_list[0])
print(my_list[-1]) #equiv a [3]
print(my_list[-2])

banana
pera
laranja


In [ ]:
# slicing 
print(my_list[:]) #todos itens
print(my_list[0:2])
print(my_list[:2])


['banana', 'abacate', 'laranja', 'pera']
['banana', 'abacate']
['banana', 'abacate']


In [ ]:
## modificando um item da lista
print(my_list)
my_list[0] = 'uva'
print(my_list)

['banana', 'abacate', 'laranja', 'pera']
['uva', 'abacate', 'laranja', 'pera']


In [ ]:
#print(my_list[start:end:step])
print(my_list[::3]) # dois em dois

['banana', 'pera']


### tuple

In [ ]:
my_tuple = (11,25,78,43.9)
print(my_tuple)
print(type(my_tuple))
my_tuple[0] = 5 # TypeError!

(11, 25, 78, 43.9)
<class 'tuple'>


TypeError: ignored

In [ ]:
my_tuple
my_list

['uva', 'abacate', 'laranja', 'pera']

## Conjunto: Set

In [ ]:
my_set = {100, 40, 'uva'}
print(my_set)
print(type(my_set))

{40, 100, 'uva'}
<class 'set'>


In [ ]:
my_set[0] #TypeError

TypeError: ignored

## Dicionario: dict

In [ ]:
my_dict = {'nome':'maria','idade':25,'fone':41999}
print(my_dict)
print(type(my_dict))

{'nome': 'maria', 'idade': 25, 'fone': 41999}
<class 'dict'>


In [ ]:
print(my_dict['nome'])
print(my_dict['idade'])

maria
25


In [ ]:
tabela = {"tempo":[0,1,2],"posicao": [1.3,5.8,10.0]}
print(tabela)

{'tempo': [0, 1, 2], 'posicao': [1.3, 5.8, 10.0]}


In [ ]:
print(tabela['tempo'])

[0, 1, 2]


## Booleano: Bool

In [ ]:
var1, var2 = True, False
print(var1,var2)
print(type(var1),type(var2))


True False
<class 'bool'> <class 'bool'>


In [ ]:
var = [1,2,[3,4]]

In [ ]:
var[2][0]

3

In [ ]:
my_list = [1,2,'a',3.4]
print(my_list[2])

a


In [ ]:
my_list = [1,2,[6,7]]
print(my_list)
print(my_list[2][0])

[1, 2, [6, 7]]
6


# Perguntas da ultima aula:

In [ ]:
# O que aconteceria se eu fizesse: x = int(2.3)? 

In [ ]:
# O que aconteceria se eu fizesse: x = str(1) e depois definisse y = x + x
# Faz sentido o resultado obtido? Porque?

In [ ]:
# defina my_dict = {'a':1,'b':2,'c':3,'d':4} e de um print": my_dict; my_dict.keys(); my_dict.values(); my_dict.items() 

# Operadores

## Aritméticos

In [ ]:
x = 5
y = 2
print(x + y) # Adicao
print(x - y) #diferenca
print(x * y) # multiplicacao
print(x / y) # divisao
print(x // y) # Floor division
print(x % y) # modulus
print(x ** y) # Exponenciacao

# Tarefas:
# 1) de um print do type de cada uma das operacoes acima, o que vc pode afirmar sobre o type final?;
# 2) defina y = 0.5 e refaça as os prints acima;
# 3) de um print do type de cada uma das operacoes par y=0.5, o que vc pode afirmar sobre o type final?;

In [ ]:
((a-b)/b)*u

0.3333333333333333

## Lógicos

In [ ]:
t,f = True,False
print(t)
print(f)
print(t,f)
print(type(t))

True
False
True False
<class 'bool'>


In [ ]:
print(t and f) # "E" LOGICO
print(t or f)  # "OU" LOGICO
print(not f)   # "NAO" LOGICO
print(t != f)  # "XOR" LOGICO (DIFERENTE)

## Relacionais

In [ ]:
x = 10
y = 7
z = 3
# > maior que "greater than"
print(x>y)   # True
print(x>y>z) #True

# < menor que "less than"
print(x<y)
print(y<x)

# == Igual a "equal to"
print(x==y) 
print(x==10)

# != não igual (diferente)
print(x != y) 
print(x != 10)

# >= maior ou igual a "greater than or equal to"
print(x >=y)
print(x >=10)

# <= menor ou igual a "less than or equal to"
print(x <= y)

In [ ]:
## atribuição

a = 7
b = 2
print(a,b)

a += b # a = a + b
print(a,b)

a = 7
b = 2
a -= b # a = a - b
print(a,b)

a=7
b=2
a *= b # a = a*b
print(a,b)

a=7
b=2
a /= b # a = a/b
print(a,b)

# tarefa: testar os casos // (floor) e % (modulus), seguindo a mesma logica

7 2
9 2
5 2
14 2
3.5 2


# Estruturas de controle

In [ ]:
## IF (SE)

number = 10
if number > 11:
  print(number)
  print(number*number)

In [ ]:
## IF (SE)

number = 10
if number > 11:
  print(number)
print(number*number)

100


In [ ]:
## IF-ELSE

number = 10
if number > 11:
  print('é maior que 11')
else:
  print('é menor que 11')

é menor que 11


# loop FOR

In [ ]:
for i in [1,2,3,4]:
  print(i)

1
2
3
4


In [ ]:
my_list = [1,2,3,4]
for i in my_list:
  print(i)

1
2
3
4


In [ ]:
my_list = ['banana','pera','uva']
for i in my_list:
  print(i)

banana
pera
uva


In [ ]:
my_tuple = (1,2,3,4)
for i in my_tuple:
  print(i)


1
2
3
4


In [ ]:
n = 10
for i in range(n):
  print(i)

0
1
2
3
4
5
6
7
8
9


# Importando bibliotecas (modulos)

In [ ]:
import math
print(math.sqrt(2))
print(math.factorial(3))

1.4142135623730951
6


In [ ]:
from math import factorial
print(math.factorial(3))
print(factorial(3))

6
6


In [ ]:
import numpy as np


In [ ]:
# criando um array de dim 1
A = np.array([1,2,3])
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# alguns atributos do array A
print(A.ndim)  # a dimensao de A
print(A.shape) # as dimensoes do array
print(A.size)  # numero de elementos de A
print(A.dtype) # tipo numerico dos elementos

1
(3,)
3
int64


In [ ]:
# Acessando os elementos:
print(A[0])
print(A[1])
print(A)

1
2
[1 2 3]


In [ ]:
# criando um array de dim 2 (tbm conhecido como matriz - na algebra linear)
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)
print(type(B))
print(B.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [ ]:
print(B[0][0]) # (1,1)
print(B[0][1]) # (1,2)

1
2


In [ ]:
# Tarefas:
#1)refaçam os dois blocos acima para o caso float e complex.
#2)refaçam o bloco "A" A = np.array([1,2,3],dtype=X), trocando X por int, float e complex

## funcoes uteis em Numpy

In [ ]:
A = np.zeros((2,2))
print(A)
B = np.ones((2,2))
print(B)
C = np.empty((3,3))
print(C)
D = np.identity(4)
print(D)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Funcao arange()
A = np.arange(0,4,1)
print(A)

[0 1 2 3]


In [ ]:
# Funcao linspace()
B = np.linspace(0,4,5)
print(B)
C = np.linspace(0,4,10)
print(C)

[0. 1. 2. 3. 4.]
[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [ ]:
# duplicando cada elemento de uma lista
a = [1,2,3,4]
b = a+a
print(a)
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
# duplicando cada elemento de um array
A = np.array([1,2,3,4])
B = A + A 
print(A)
print(B) 

[1 2 3 4]
[2 4 6 8]


In [ ]:
C = 3*A
print(A)
print(C)

[1 2 3 4]
[ 3  6  9 12]


In [ ]:
A = np.array([[1,2],[3,4]])
D = A*A
print(A)
print(D)

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]


In [ ]:
# NOTA: as operacoes sao feitas elemento a elemento!

In [ ]:
E = A@A
F = A.dot(A)
print(E)
print(F)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [ ]:
A = np.arange(1,5,1)
print(A)
B = np.arange(1,5,1).reshape(2,2)
print(B)

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
A