<a href="https://colab.research.google.com/github/crisfisico/minicurso-python/blob/main/Aula_02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## A versao em uso do Python

In [ ]:
!python --version

Python 3.7.11


# Biblioteca Numpy

In [1]:
import numpy as np
print(np.__version__)

1.19.5


In [ ]:
# criando um array de dim 1
A = np.array([1,2,3])
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# alguns atributos do array A
print(A.ndim)  # a dimensao de A
print(A.shape) # as dimensoes do array
print(A.size)  # numero de elementos de A
print(A.dtype) # tipo numerico dos elementos

1
(3,)
3
int64


In [ ]:
# Acessando os elementos:
print(A[0])
print(A[1])
print(A)

1
2
[1 2 3]


In [ ]:
# criando um array de dim 2 (tbm conhecido como matriz - na algebra linear)
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)
print(type(B))
print(B.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [ ]:
print(B[0][0]) # (1,1)
print(B[0][1]) # (1,2)

1
2


In [ ]:
# Tarefas:
#1)refaçam os dois blocos acima para o caso float e complex.
#2)refaçam o bloco "A" A = np.array([1,2,3],dtype=X), trocando X por int, float e complex

## funcoes uteis em Numpy

In [ ]:
A = np.zeros((2,2))
print(A)
B = np.ones((2,2))
print(B)
C = np.empty((3,3))
print(C)
D = np.identity(4)
print(D)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Funcao arange()
A = np.arange(0,4,1)
print(A)

[0 1 2 3]


In [ ]:
# Funcao linspace()
B = np.linspace(0,4,5)
print(B)
C = np.linspace(0,4,10)
print(C)

[0. 1. 2. 3. 4.]
[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]


In [ ]:
# duplicando cada elemento de uma lista
a = [1,2,3,4]
b = a+a
print(a)
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
# duplicando cada elemento de um array
A = np.array([1,2,3,4])
B = A + A 
print(A)
print(B) 

[1 2 3 4]
[2 4 6 8]


In [ ]:
C = 3*A
print(A)
print(C)

[1 2 3 4]
[ 3  6  9 12]


In [ ]:
A = np.array([[1,2],[3,4]])
D = A*A
print(A)
print(D)

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]


In [ ]:
# NOTA: as operacoes sao feitas elemento a elemento!

In [ ]:
E = A@A
F = A.dot(A)
print(E)
print(F)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [2]:
A = np.arange(1,5,1)
print(A)
B = np.arange(1,5,1).reshape(2,2)
print(B)

[1 2 3 4]
[[1 2]
 [3 4]]


## Algebra linear: modulo `linalg` 

In [3]:
np.linalg.det(B)

-2.0000000000000004